# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 777b7330119fa9135afb1fea6e7ce3edf5a0b11ac53dfc7bbd084075d6fa240d2bc613919ccf77a53f8aa20a78a7b249445ee09d281e092e50d4a3a8029c3709

test:
  secret_key_base: 51d01c8a92bb69c1f2c2f952f91df8319c3da594cbbe7cb1af2bc80bf16ce24d6f7e87b81d92e247d69c3721a3213390752a3f6dfccd0cf38bfddc67ab612602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
